<%-- 所有页面的公用头部 --%>
<%@ page contentType="text/html; charset=UTF-8" language="java" %>
<%@ include file="/pub/taglibs.inc"%>
<%--struts2标签 --%>
<s:head theme="xhtml"/>    
<sj:head debug="true" compressed="false" jquerytheme="xhtml" 
	customBasepath="themes" defaultIndicator="myDefaultIndicator" defaultLoadingText="Please wait ..."/>
<!-- 应用的样式 -->
<link href="${baseURL}/themes/default/css/sdApp.css" rel="stylesheet" type="text/css" /> 

